remote_theme: pmarsceill/just-the-docs
title: "IsCodigo | Blog"
description: "Blog de Enrique Avila | UNAH"
url: "https://iscodigo.github.io"
logo: "assets/logo.png"

# Configuración de navegación
nav_enabled: true
search_enabled: true

# Soporte para diagramas
has_mermaid: true
mermaid:
  version: "10"

lang: "es"

# Estética
color_scheme: light
