remote_theme: sighingnow/jekyll-gitbook
title: "IsCodigo | Blog"
description: "Blog de Enrique Avila | UNAH"
url: "https://iscodigo.github.io"
logo: "assets/logo.png"

# Configuración de navegación
search_enabled: true
syntax_highlighter_style: monokai

# Índice de encabezados dentro de la página activa
toc:
  enabled: true
  h_min: 2
  h_max: 3

# Soporte para diagramas
has_mermaid: true
mermaid:
  version: "10"

lang: "es"

# Estética
color_scheme: light
