mindmap
    root[Hilos - Sección 2.2]
        MOTIVACION
            Procesador de texto
            Servidor Web workers
            Solapar cómputo y E/S
        MODELO
            Proceso igual recursos
            Hilo igual ejecución
            Recursos compartidos vs privados
        IMPLEMENTACION
            User space ULT
            Kernel space KLT
            Híbrido ULT-KLT
        MECANISMOS
            POSIX Threads Pthreads
            Activaciones del planificador
            Pop-up threads
        DIFICULTADES
            Variables globales errno
            Bibliotecas no reentrantes
            Manejo de señales
            Múltiples pilas
